### ISSUE TITLE
Need to show comparison to other analysis

### ISSUE THREAD

**Issue by lcarasik** [hughfeehan353/PACCMAN#9]

**Comment by hughfeehan353** [comment]
[Mazur2017_Article_NumericalAndExperimentalEvalua.pdf](https://github.com/hughfeehan353/PACCMAN/files/6185053/Mazur2017_Article_NumericalAndExperimentalEvalua.pdf)

**Comment by lcarasik** [comment]
Mazur 2017 - Numerical and experimental evaluation of a conformally cooled H13 steel injection mould manufactured with selective laser melting
